### PR TITLE
fix: use request->get() instead of request->getAlpha()

### PR DESCRIPTION
**Pull request by JoniJnm**
https://github.com/CodelyTV/php-ddd-example/commit/f7e7bed9c0596e4a5587559604c8731bc69a19cb broke some actions

If we use `request->getAlpha` we loss some chars like dash, space, numbers, etc

### CODE REVIEW

**Comment by JoniJnm** [comment]
fixed: https://github.com/CodelyTV/php-ddd-example/pull/311

**Comment by JavierCane** [comment]
🎉 good one!

thx!

**Comment by JavierCane** [comment]
Sorry for not reviewing this PR on time. It looks good to me, but I don't know if you closed it for some reason 🙏

Would you like to reopen and merge it?

**Comment by JoniJnm** [comment]
you fixed the problem with this PR: https://github.com/CodelyTV/php-ddd-example/pull/311

**Pull request closed without merging**
